modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/wolfieboy09/PlayerFinder/issues"
license = "MIT"

[[mods]]
modId = "modernplayerfinder"
version = "${version}"
displayName = "Player Locator"
authors = "Wolfieboy09"
description = '''
This mod allows server admins to locate players on the server
'''
logoFile = "icon.png"

[[dependencies.modernplayerfinder]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.modernplayerfinder]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.modernplayerfinder]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "SERVER"
